[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Subdomain redirects voor je 5 platforms
[[redirects]]
  from = "https://my.careservice.es/*"
  to = "https://careservice.es/my/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://book.careservice.es/*"
  to = "https://careservice.es/book/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://pro.careservice.es/*"
  to = "https://careservice.es/pro/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://admin.careservice.es/*"
  to = "https://careservice.es/admin/:splat"
  status = 200
  force = true

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

# Cache optimization
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 